[package]
name = "store"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
domain = { path = "../domain" }
bindung = { path = "../bindung" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
regex = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
